language: cpp

# want to include osx in the future
os:
  - linux

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

cache:
  directories:
    # Save opencv build
    - $TRAVIS_BUILD_DIR/opencv/
    - $TRAVIS_BUILD_DIR/opencv_contrib/

notifications:
  email: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.7
    - valgrind
    - pkg-config
    - build-essential

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - ${CXX} -v

# Getting opencv with contrib
  - git clone --branch 3.2.0 https://github.com/opencv/opencv.git || true
  - git clone --branch 3.2.0 https://github.com/opencv/opencv_contrib.git || true
  - cd opencv
  - mkdir build || true
  - cd build
  - cmake -D CMAKE_BUILD_TYPE=RELEASE
          -D CMAKE_INSTALL_PREFIX=/usr/local
          -D WITH_OPENGL=ON
          -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules ..
  - make -j5
  - sudo make install
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
  - sudo ldconfig
  - echo "OpenCV installed."
  - cd ../..

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
